name: Slack Notification

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took # selectable (default: repo,message)
        env:
          slack_webhook_url: ${{ secrets.SLACK_WEBHOOK_URL }}
          slack_username: Github
        if: always()

